### ISSUE TITLE
本が誤植があります

### ISSUE THREAD

**Issue by ockun** [nshiro/Larave-5.5-sample#1]
https://github.com/nshiro/Larave-5.5-sample/blob/5d47c47dcb3b4e42957063035213674a31b6e8c8/app/Http/Controllers/SignupController.php#L32

本では
```
$data = $this->validate([ 
```
となっております

**Comment by nshiro** [comment]
ご連絡ありがとうございます。
読み進めていただけると分かるかと思いますが、最初は、$this->validate([ の形を紹介していますが、
後に、$request->validate([ の形を紹介し、そちらを最終形としております。
よろしくお願いします。
